
Portada
Título del proyecto: Análisis de Base de Datos de Fast Food
Institución: Fast Food Analysis Inc. (Logo opcional)

Introducción
Este informe presenta un análisis exhaustivo de la base de datos de una cadena de comida rápida, que incluye la eficiencia de los mensajeros, el análisis de ventas por origen de orden, la productividad de los empleados, la demanda de productos por horario, la comparación de ventas mensuales y el análisis de fidelidad del cliente. Los datos han sido extraídos y analizados para proporcionar una visión clara de las operaciones y rendimiento de la empresa.

Desarrollo del Proyecto
Se ha creado una base de datos denominada fast_food_db con varias tablas para gestionar clientes, sucursales, mensajeros, orígenes de orden, tipos de pago, categorías de productos, departamentos, productos, empleados, órdenes y artículos de órdenes. Estas tablas se diseñaron para capturar información relevante sobre cada aspecto de las operaciones de la empresa.

Resultados y Consultas
Eficiencia de los Mensajeros
Pregunta: ¿Cuál es el tiempo promedio desde el despacho hasta la entrega de los pedidos gestionados por todo el equipo de mensajería?
sql
Copy code
-- Calculate the average time from dispatch to delivery for all messengers
SELECT AVG(DATEDIFF(MINUTE, o.dispatch_datetime, o.delivery_datetime)) AS 'Average Delivery Time (minutes)'
FROM orders o
INNER JOIN messengers m ON o.messenger_id = m.messenger_id;
GO
Resultado: El tiempo promedio de entrega es de 30 minutos.
Análisis de Ventas por Origen de Orden
Pregunta: ¿Qué canal de ventas genera más ingresos?
sql
Copy code
-- Total sales by sales channel
SELECT s.origin_name, SUM(o.total_amount) AS 'Total Sales'
FROM orders o
INNER JOIN order_origins s ON o.order_origin_id = s.order_origin_id
GROUP BY s.origin_name
ORDER BY 'Total Sales' DESC;
GO
Resultado: Los datos indican un total de ventas de 21,694.04 en el origen de ventas.
Productividad de los Empleados
Pregunta: ¿Cuál es el nivel de ingreso generado por empleado?
sql
Copy code
-- Total income generated by each employee
SELECT e.employee_name, SUM(o.total_amount) AS 'Total Income Generated'
FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
GROUP BY e.employee_name
ORDER BY 'Total Income Generated' DESC;
GO
Resultado:
John Doe: 4,414.04
Ethan Martinez: 4,380.00
Olivia García: 4,340.00
Jane Smith: 4,300.00
Lucas Miller: 4,260.00
Análisis de Demanda por Horario y Día
Pregunta: ¿Cómo varía la demanda de productos a lo largo del día?
sql
Copy code
-- Demand analysis by time of day
SELECT sale_time, COUNT(*) AS 'Number of Orders'
FROM orders
GROUP BY sale_time;
GO
Resultado:
Morning: 8 orders
Afternoon: 8 orders
Evening: 4 orders
Comparación de Ventas Mensuales
Pregunta: ¿Cuál es la tendencia de los ingresos generados en cada periodo mensual?
sql
Copy code
-- Monthly sales trend
SELECT YEAR(dispatch_datetime) AS 'Year', MONTH(dispatch_datetime) AS 'Month', SUM(total_amount) AS 'Total Sales'
FROM orders
GROUP BY YEAR(dispatch_datetime), MONTH(dispatch_datetime)
ORDER BY YEAR(dispatch_datetime), MONTH(dispatch_datetime);
GO
Resultado:
2023, January: 4,414.04
2023, February: 4,300.00
2023, July: 4,260.00
2023, August: 4,340.00
2023, September: 4,380.00
Análisis de Fidelidad del Cliente
Pregunta: ¿Qué porcentaje de clientes son recurrentes versus nuevos clientes cada mes?
sql
Copy code
-- Percentage of recurring versus new customers
WITH CustomerOrders AS (
    SELECT customer_id, COUNT(*) AS order_count
    FROM orders
    GROUP BY customer_id
)
SELECT 
    CASE 
        WHEN order_count > 1 THEN 'Recurring'
        ELSE 'New'
    END AS 'Customer Type',
    COUNT(*) AS 'Number of Customers',
    (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM CustomerOrders)) AS 'Percentage'
FROM CustomerOrders
GROUP BY 
    CASE 
        WHEN order_count > 1 THEN 'Recurring'
        ELSE 'New'
    END;
GO
Resultado:
Recurring: 5 customers (100%)

Optimización y Sostenibilidad
La base de datos fue optimizada mediante la implementación de índices en las columnas de búsqueda más frecuentes y la normalización para evitar redundancias. Se garantizará la sostenibilidad a largo plazo mediante una revisión periódica de los esquemas y una planificación para escalabilidad futura.

Desafíos y Soluciones
Desafío: Manejo de datos inconsistentes y falta de datos en ciertas tablas.
Solución: Se realizó una limpieza de datos y ajustes en las consultas SQL para manejar situaciones donde los datos podían ser nulos o inconsistentes.
Desafío: Implementación de consultas complejas con datos grandes.
Solución: Se optimizaron las consultas y se emplearon índices adecuados para mejorar el rendimiento.

Síntesis
Este informe muestra una visión integral del desempeño de la empresa de comida rápida mediante el análisis de diversos aspectos operacionales. Las conclusiones y recomendaciones basadas en los datos proporcionan una base sólida para la toma de decisiones empresariales.

Reflexión Personal
Durante el proyecto, he adquirido habilidades significativas en el análisis de bases de datos, la creación de consultas SQL avanzadas y la interpretación de resultados para tomar decisiones informadas. Si tuviera que comenzar de nuevo, mantendría el enfoque en la optimización de consultas y en una planificación exhaustiva de la estructura de la base de datos. Sin embargo, consideraría implementar herramientas adicionales para un análisis más profundo y la visualización de datos.

